name: ffi-example
author: "Artem Mavrin"
maintainer: "artemvmavrin@gmail.com"
copyright: "2021 Artem Mavrin"

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  c-sources: src/lib.c
  ghc-options:
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

executables:
  length:
    main: Main.hs
    source-dirs: app/length
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - ffi-example
  max:
    main: Main.hs
    source-dirs: app/max
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - ffi-example

tests:
  test:
    main: Main.hs
    source-dirs: test/
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -O0
    dependencies:
      - ffi-example
      - hspec >= 0.8.2
      - QuickCheck >= 2.14.2
